import {
    faArrowLeft, faArrowRight,
    faBars, faBold,
    faBook,
    faBookmark, faBroom,
    faChevronDown,
    faChevronRight, faCode,
    faColumns,
    faCompactDisc,
    faEnvelopeOpenText,
    faEye,
    faFile,
    faFileAlt,
    faFileAudio,
    faFileCode, faFilter,
    faFolder, faHeading,
    faHome,
    faImage,
    faImages, faItalic,
    faLightbulb, faList, faListOl, faListUl,
    faMemory, faMinus,
    faMoon, faParagraph,
    faPencilAlt,
    faPlus, faQuoteLeft, faRedo, faRulerHorizontal,
    faSearch, faStrikethrough,
    faSun,
    faTextHeight,
    faTimes, faTrash, faUndo,
    faUserSecret,
    faVideo
} from "@fortawesome/free-solid-svg-icons";
import {library} from "@fortawesome/fontawesome-svg-core";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

library.add(
    faUserSecret,
    faTimes,
    faBars,
    faEye,
    faFolder,
    faFile,
    faFileAlt,
    faFileCode,
    faImage,
    faVideo,
    faColumns,
    faFileAudio,
    faTextHeight,
    faEnvelopeOpenText,
    faLightbulb,
    faHome,
    faSearch,
    faBook,
    faBookmark,
    faImages,
    faPlus,
    faCompactDisc,
    faMemory,
    faMoon,
    faSun,
    faChevronDown,
    faChevronRight,
    faPencilAlt,
    faMinus,
    faTrash,
    faFilter,
    faBold,
    faItalic,
    faStrikethrough,
    faCode,
    faHeading,
    faRedo,
    faUndo,
    faList,
    faListOl,
    faListUl,
    faFileCode,
    faQuoteLeft,
    faRulerHorizontal,
    faParagraph,
    faBroom,
    faArrowLeft,
    faArrowRight,
)

export default function (app) {
    app.component("FontAwesomeIcon", FontAwesomeIcon)
}
