import {
    faBars,
    faBook,
    faBookmark,
    faChevronDown,
    faChevronRight,
    faColumns,
    faCompactDisc,
    faEnvelopeOpenText,
    faEye,
    faFile,
    faFileAlt,
    faFileAudio,
    faFileCode, faFilter,
    faFolder,
    faHome,
    faImage,
    faImages,
    faLightbulb,
    faMemory, faMinus,
    faMoon,
    faPencilAlt,
    faPlus,
    faSearch,
    faSun,
    faTextHeight,
    faTimes, faTrash,
    faUserSecret,
    faVideo
} from "@fortawesome/free-solid-svg-icons";
import {library} from "@fortawesome/fontawesome-svg-core";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

library.add(
    faUserSecret,
    faTimes,
    faBars,
    faEye,
    faFolder,
    faFile,
    faFileAlt,
    faFileCode,
    faImage,
    faVideo,
    faColumns,
    faFileAudio,
    faTextHeight,
    faEnvelopeOpenText,
    faLightbulb,
    faHome,
    faSearch,
    faBook,
    faBookmark,
    faImages,
    faPlus,
    faCompactDisc,
    faMemory,
    faMoon,
    faSun,
    faChevronDown,
    faChevronRight,
    faPencilAlt,
    faMinus,
    faTrash,
    faFilter
)

export default function (app) {
    app.component("FontAwesomeIcon", FontAwesomeIcon)
}
